import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import MainPage from "../components/MainPage/MainPage";
import Header from "../components/Header/Header";
import {useEffect} from "react";
import {useDispatch} from "react-redux";
import {authUser} from "../store/auth-reducer/auth-thunks";
import MainLayout from "../components/MainLayout/MainLayout";

export default function Home() {
  const dispatch = useDispatch()

  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </MainLayout>
  )
}
